### PR TITLE
Add telnet weather / generator / games

### PR DESCRIPTION
**Pull request by mcthomas**
Also swapped the nethack server, added a single BBS, and removed a MUD.

### CODE REVIEW

**Comment by chubin** [comment]
@mcthomas Why have you removed MUDs?

**Comment by mcthomas** [comment]
I initially added two because the repo didn't have any MUDs, but there's nearly limitless MUD servers out there, so rather than flooding the repo with MUDs I thought it better to just include the most popular MUD.  Likewise for the BBS server.

**Comment by chubin** [comment]
Maybe we should add an additional list (something like: MUD.md) and add a link to it to README.md?

**Comment by mcthomas** [comment]
That's a good idea, maybe one for BBS servers too, or a combined .md for both.

**Comment by chubin** [comment]
Feel free to add them: MUD.md & BBS.md

**Pull request merged**
