### PR TITLE
A curl tool that shows Covid-19 statistics for the visitor's Country.

### PR DESCRIPTION
**Pull request by catman85**
Simply type  `curl snf-878293.vm.okeanos.grnet.gr`

Repo: https://github.com/catman85/TermApp-Node-Typesript-Docker-Express

Originally inspired by wttr.in which I use daily.

### CODE REVIEW

**Comment by chubin** [comment]
@catman85  Cool service, Dimtris, but the name is very bad. Do you have any plans for changing the name?

**Comment by catman85** [comment]
@chubin Thank you! Unfortunately I don't have any plans for changing the domain currently. Any future change will be visible from my github repo.

**Comment by eimon96** [comment]
I wouldn't mind making an alias for this.

**Comment by chubin** [comment]
@eimon96 In what domain?

**Comment by chubin** [comment]
JFYI: I added also two additional curl-based trackers to the list:

* https://github.com/sagarkarira/coronavirus-tracker-cli
* https://github.com/trackercli/covid19-tracker-cli

**Pull request merged**
