### PR TITLE
Adding getnews.tech

### PR DESCRIPTION
**Pull request by kebertxela**

### CODE REVIEW

**Comment by chubin** [comment]
Wow! Very col
Thank you @kebertxela for adding it.

**Comment by kebertxela** [comment]
I thought so too, thanks for the quick merge :smile:

**Comment by chubin** [comment]
We should probably ping @omgimanerd, thank him for the beautiful service,
and inform him that the service was now added to our directory :)

@omgimanerd, thank you for getnews.tech!

**Comment by omgimanerd** [comment]
Thanks so much for adding my project!

**Pull request merged**
